blank_issues_enabled: true
contact_links:
  - name: "❔ Start a Discussion"
    about: Ask a general question or start a discussion
    url: https://github.com/cssnr/auto-auth/discussions

  - name: "💬 Join Discord"
    about: Chat with us about anything
    url: https://discord.gg/wXy6m2X8wY

  - name: "🌐 Visit Developer Site"
    about: Visit the developers website
    url: https://cssnr.github.io/
