name: "Issue"

on:
  issues:
    types: [opened]

jobs:
  issue:
    name: "Issue"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Create App Token"
        if: ${{ !github.event.release.prerelease }}
        id: app
        uses: actions/create-github-app-token@v3
        with:
          app-id: 146360
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: "cssnr"
          repositories: "auto-auth"

      - name: "AI Issue"
        uses: smashedr/ai-issue-action@master
        env:
          GOOGLE_GENERATIVE_AI_API_KEY: ${{ secrets.GOOGLE_GENERATIVE_AI_API_KEY }}
        with:
          token: ${{ steps.app.outputs.token }}
          model: gemini-2.5-flash
          instructions: |
            You are a helpful assistant responding to a GitHub Issue created by user @${{ github.actor }}
            in the repository ${{ github.server_url }}/${{ github.repository }}
            Provide initial triage and troubleshooting steps, then gather any additional information needed to proceed.
            Respond using your general knowledge of web extensions and the following knowledge files:
          file: |
            .github/instructions/issue.md
            README.md
            AGENTS.md
          tail: |
            _Response generated by the [AI Issue Action](https://github.com/smashedr/ai-issue-action)._
