name: "Test"

on:
  workflow_dispatch:
  #schedule:
  #  - cron: "18 18 * * 1,3,5"
  push:
    branches: [master]
    paths: &paths
      - ".github/workflows/test.yaml"
      - "src/**"
      - "tests/**"
      - "gulpfile.js"
      - "manifest*.json"
      - "package*.json"
  pull_request:
    branches: [master]
    paths: *paths

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: ${{ !contains(github.event.head_commit.message, '#notest') }}

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Setup Node 24"
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: "Install"
        run: |
          npm ci

      - name: "Test"
        id: test
        run: |
          npm run test

      - name: "Push Artifacts"
        uses: cssnr/push-artifacts-action@master
        if: ${{ github.event_name == 'pull_request' }}
        continue-on-error: true
        with:
          source: "tests/screenshots/"
          dest: "/static"
          host: ${{ secrets.RSYNC_HOST }}
          user: ${{ secrets.RSYNC_USER }}
          pass: ${{ secrets.RSYNC_PASS }}
          port: ${{ secrets.RSYNC_PORT }}
          webhost: "https://artifacts.hosted-domains.com"
          #webhook: ${{ secrets.DISCORD_WEBHOOK }}
          #token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Schedule Failure Notification"
        uses: sarisia/actions-status-discord@eb045afee445dc055c18d3d90bd0f244fd062708 # v1.16.0
        if: ${{ failure() && github.event_name == 'schedule' }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          description: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
